version: "3.7"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    restart: always

  web:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port ${WEB_PORT}
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      - db
      - redis

  redis:
    image: redis:6-alpine
    restart: always

volumes:
  postgres_data:
